### ISSUE TITLE
Des détails

### ISSUE THREAD

**Issue by MarioSto** [LaCreArthur/RodyAIbiza#1]
Il y a quelques petits détails qui diffèrent des jeux originaux:
- le curseur apparaît dans l'introduction où on doit attendre la fin de la musique contrairement aux jeux originaux.
- il est possible de passer l'introduction en perdant le focus de la fenêtre. (après c'est pas forcément grave vu la durée de la musique ^^) (edit: toutes les musiques peuvent être skippées)
- le curseur dans le menu de sélection de niveau est le curseur de base de Windows alors que c'est censé être un doigt tendu.
- et enfin la voix du synthétiseur est parfois un peu saccadée (ex: le "non" est un peu découpé). Certaines répliques de Masticot sont différentes de celles du jeu original (ex: "Non" -> "Non, recommence"; "Ce n'est pas ça" -> "Ce n'est pas ça, essaie de nouveau").

Pour le reste c'est vraiment bluffant, on dirait un des jeux originaux avec tout de même un peu de nouveauté avec le New Game ++ qui est appréciable. Bravo !
Bonne chance pour la suite et si tu as besoin de testeurs à nouveau, compte sur moi :)

**Comment by LaCreArthur** [comment]
3 premiers points OK,
4eme point : je prépare une build spéciale avec beaucoup de paroles pour pouvoir améliorer au maximum le synthétiseur. 
Merci de ton aide :+1:
