### ISSUE TITLE
Négation inexacte

### ISSUE THREAD

**Issue by chocomilk26** [LaCreArthur/RodyAIbiza#2]
Mastico dit : 
-"Recommence" au lieu de "Non, recommence".

-"Non" au lieu de "Non, cherche encore".

-"Ce n'est pas ça" au lieu de "Ce n'est pas ça, essaye de nouveau".

**Comment by LaCreArthur** [comment]
Merci pour ta participation. les réponses de Mastico sont en effet raccourcies pour accélérer les phases de test. Elles seront améliorées pour la version finale
